### PR TITLE
refactor: Insert_Replace values chould be Select type

### LINKED ISSUE #2165: Insert_Replace object has Select for values prop
**Describe the bug**
The **Insert_Replace** interface has a values property that is of type **InsertReplaceValue[]**
However, the values object holds a **Select** object as its possible from **INSERT INTO table1 SELECT * from table2**

**Database Engine**
MySQL

**To Reproduce**
Use a query like below and you'd see values object which is of type **InsertReplaceValue[]** holds a Select AST
INSERT INTO user_stats (user_id, total_spend) 
SELECT user_id, SUM(total) 
FROM orders 
WHERE created_at >= '2023-01-01' 
GROUP BY user_id`,

**Expected behavior**
Object type should be updated for Insert_Replace.values

**Screenshots**
image
image

**Additional context**
Using latest version 5.3.2

### PR DESCRIPTION
**Pull request by taozhi8833998**
- fix #2165

### CODE REVIEW

**Comment by cansardan** [comment]
did not open a new issue
but theres also other props in insert object, specifically on_duplicate_update which need to access
`{
  type: "insert",
  table: [
    {
      db: "mysql",
      table: "my_table",
      as: null,
    },
  ],
  columns: [
    "id",
    "value",
  ],
  values: [
    {
      type: "expr_list",
      value: [
        {
          type: "number",
          value: 1,
        },
        {
          type: "number",
          value: 1,
        },
      ],
    },
  ],
  partition: null,
  prefix: "into",
  on_duplicate_update: {
    keyword: "on duplicate key update",
    set: [
      {
        column: "value",
        value: {
          type: "number",
          value: 2,
        },
        table: null,
      },
    ],
  },
}`

**Comment by taozhi8833998** [comment]
> did not open a new issue but theres also other props in insert object, specifically on_duplicate_update which need to access `{ type: "insert", table: [ { db: "mysql", table: "my_table", as: null, }, ], columns: [ "id", "value", ], values: [ { type: "expr_list", value: [ { type: "number", value: 1, }, { type: "number", value: 1, }, ], }, ], partition: null, prefix: "into", on_duplicate_update: { keyword: "on duplicate key update", set: [ { column: "value", value: { type: "number", value: 2, }, table: null, }, ], }, }`

added it.

**Comment by cansardan** [comment]
thanks. when can we expect the changes be published?

**Comment by taozhi8833998** [comment]
> thanks. when can we expect the changes be published?

The new version has been published.

**Pull request merged**
