### PR TITLE
feat: support escape after like op in Mysql and MariaDB

### PR DESCRIPTION
**Pull request by Konosh93**
Fixes
- https://github.com/taozhi8833998/node-sql-parser/issues/1460

### Note
@taozhi8833998 
I added a fix similar to pg. Please have a look when you have time.

### CODE REVIEW

**Comment by Konosh93** [comment]
@taozhi8833998 Can you kindly have a look at this PR. Is there any thing missing or changes need to be made?

**Comment by taozhi8833998** [comment]
> @taozhi8833998 Can you kindly have a look at this PR. Is there any thing missing or changes need to be made?

I have written some comments on it weeks ago, can you take a look and make some detail explain?

image

since you do not reply to the review,  so I open a new pr for it. please check it. If you can make comment to my reviews, I can close my pr and merge yours.

**Comment by Konosh93** [comment]
@taozhi8833998 
Thank you for the reply. 

> I have written some comments on it weeks ago, can you take a look and make some detail explain?

I cannot view your comments. Have you published them? The screenshot shows that they are still pending.

**Comment by taozhi8833998** [comment]
@Konosh93 Sorry it's my bad. I forgot to submit the reviews, and you can't see them. Thank you for the pr, if you have any further pr please let me know. Thanks for ur contribution again.

**Pull request closed without merging**
