### PR TITLE
Use webpack + HMR unit tests + one build bundle per language

### PR DESCRIPTION
**Pull request by oguimbal**
First & foremost: This pull request is quite heavy, and is a prerequisite for me given that I intend to build on your library.
I could totaly understand if you dont want to merge it, given that I changed the way you release your bundle, and the build tools you chose. However, it should be iso-functional with your build tools.
If you dont, I'm totally ok with that, I would release my own version of your bundle to get only the bits I'm using, and get rid of 700kB of parsers I dont use :)

Here is, in summary, what has changed:
- I use webpack with some dark magic to build a single bundle containing all parser, and one "light" bundle per parser (which allows to choose a bundle which is ~8x lighter if you only use one language). Each bundle also has its UMD counterpart... Check the screenshot below to see what the new built output looks like.
- I use vscode, with [my own implementation of vscode-mocha-test-adapter ](https://github.com/oguimbal/vscode-mocha-test-adapter) which allows to run and/or debug unit tests almost instantly using HMR (hot-module-reload). The experience is quite pleasant, I invite you to try it :) - see attached gifs... a realtime preview.
- You can no longer use `npm publish` to relase the package... you should rather use `npm run release`, which publishes the `output/prod` directory.

You will notice that `index.d.ts` is now almost empty, and that its content has migrated to `types.d.ts` ... this is because index.d.ts is copied once per bundle (index.d.ts, mysql.d.ts, mysql.umd.d.ts, db2.d.ts, etc), all reexporting a single types.d.ts.
... this should conflict with your current pull request, sorry :/

Code coverage & tests should still be OK :)

New list of released bundles
image

Run all tests... 1sec.
7e9c5927-579a-4c40-9cd2-66190246bd66

Debug a test... 1sec iteration between save and breakpoint hit.
95dfaedd-1707-4402-88fe-d0142738f053

### CODE REVIEW

**Comment by oguimbal** [comment]
Mmmh... i'm not sure why code coverage failed... `npm run coverLocal` reports this:

image

**Comment by taozhi8833998** [comment]
@oguimbal I will review it this weekend, and I am glad to merge it to improve the performance. Thank you for ur hard work on it.

**Comment by taozhi8833998** [comment]
pegjs should support modular grammar #100, and I will using @oguimbal way to split different databases currently.

**Comment by taozhi8833998** [comment]
@oguimbal I have Invited you as a collaborator to node-sql-parser module, you can push your commit to this project directly, so we can work together more efficient.

**Comment by oguimbal** [comment]
Thanks !

**Comment by taozhi8833998** [comment]
@oguimbal  can you push your commit as a branch to the repository, so we can do it together.

**Comment by oguimbal** [comment]
Oh sure sorry, I did not understand that :)
I pushed it to hmr-oguimbal branch.

**Comment by oguimbal** [comment]
@taozhi8833998  My other pull request #388 builds on this.

**Comment by taozhi8833998** [comment]
@oguimbal ok, I get the branch.

**Comment by taozhi8833998** [comment]
close it since #388 include it

**Pull request closed without merging**
