### PR TITLE
"Automatic" AST type generation

### PR DESCRIPTION
**Pull request by oguimbal**
I've implemented kind-of-a-hack that allows to automatically build an ast type definition from pegjs files.
This allows to have a strongly consistent, up-to-date, and language specific version of the AST interface.

It relies on the structure of pegjs, which strongly relates to generated types.
The hacky part comes from the fact that there is no way to know for sure the type returned by nodes which execute JS.
=> For them, you must declare a type in a comment header of each code block.

See the generated file `ast/postgresql.ts`, which is quite usable as it is to build a Typescript AST visitor.

NB: I only implemented the types for postgresql.pegjs (which is the one I'm interested about...)

Let me know if this seems relevant to you :)

Usage:

```typescript
import {start} from 'node-sql-parser/ast/postgresql';
const { Parser } = require('node-sql-parser/postgresql');

const parser = new Parser();
const parsed = parser.astify('select * from test') as any as start | start[];
// 👉 'parsed' is now strongly typed !
```

### CODE REVIEW

**Comment by taozhi8833998** [comment]
@oguimbal I am reviewing ur two pr, sorry for the delay, I will merge it in two days. Thanks for ur patience.

**Comment by taozhi8833998** [comment]
@oguimbal  I am trying to make the code match the style used before, the code is in RC state now.

**Comment by taozhi8833998** [comment]
so you can close pr #387? we just merge the current pr #388  only. right?

**Comment by oguimbal** [comment]
@taozhi8833998  Yes, this PR includes them both

**Comment by taozhi8833998** [comment]
@oguimbal I have published `3.0.1` version for the feature, give it a shot. Thanks for ur pr on that, it's great!!

```
const { Parser } = require('node-sql-parser')
// or import the specified database only, get more on README
// const { Parser } = require('node-sql-parser/build/mysql') 
const parser = new Parser()
const ast = parser.astify("call sp(1, 2, '23', @version)")
const sql = parser.sqlify(ast)
```

**Comment by oguimbal** [comment]
Thanks :)

**Pull request merged**
