### PR TITLE
Added support for additional snowflake data types

### PR DESCRIPTION
**Pull request by create-new-entity**
Hello,

We have been using node-sql-parser as part of our project. Thanks for this package!

This PR is an attempt to fix this issue: https://github.com/taozhi8833998/node-sql-parser/issues/1912

Please leave comments if needed.

Thanks!

### CODE REVIEW

**Review by taozhi8833998 — APPROVED** [review]
agree

**Comment by taozhi8833998** [comment]
@create-new-entity Thanks for the great pr!!!

**Comment by Kjue** [comment]
@taozhi8833998 Lovely! I see you added it also to 5.2.0 milestone too. Is there some schedule to expect for that release? Cheers!

**Comment by taozhi8833998** [comment]
@Kjue The release is scheduled for next weekend

**Comment by taozhi8833998** [comment]
@Kjue Thank you for your patience. The latest release, version 5.2.0, has been issued.

**Comment by Kjue** [comment]
Wonderful! We really appreciate it, and we'll be interacting more in the future as well. Thank you!

**Comment by taozhi8833998** [comment]
@Kjue Great to hear that! Looking forward to more collaborations in the future.

**Pull request merged**
