### PR TITLE
feat: support set to value in pg

### LINKED ISSUE #1760: Postgres: Unable to parse BEGIN, COMMIT, SET search_path TO
**Describe the bug**
Unable to parse a few valid Postgres queries

**Database Engine**
PostgreSQL.

**To Reproduce**
-the SQL that be parsed
```js
const sql = `
BEGIN;
SET search_path TO ht_hyt; 
COMMIT;
`;

```
-the node-sql-parser version 4.17.0
-the node version 20

**Expected behavior**
Should be able to parse these 3 queries

### PR DESCRIPTION
**Pull request by taozhi8833998**
- fix #1760

### CODE REVIEW

**Comment by karanssj4** [comment]
@taozhi8833998 how to handle BEGIN and COMMIT as well?

**Comment by taozhi8833998** [comment]
> @taozhi8833998 how to handle BEGIN and COMMIT as well?

@karanssj4 added it now.

**Comment by karanssj4** [comment]
@taozhi8833998 BEGIN and COMMIT could be independent queries as well. They still seem to fail

**Comment by taozhi8833998** [comment]
> @taozhi8833998 BEGIN and COMMIT could be independent queries as well. They still seem to fail

got it, reopen the issue.

**Pull request merged**
